name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build project
      - name: Build project
        run: |
          npm install
          npm run build

      # Create env file
      - name: Create environment file
        run: |
          echo "DATABASE_URL=${{ github.DATABASE_URL }}" > .env
          echo "PORT=${{ github.PORT }}" >> .env
          echo "ELECTRON_PORT=${{ github.ELECTRON_PORT }}" >> .env
          echo "JWT_SECRET=${{ github.JWT_SECRET }}" >> .env
          echo "CLOUD_PROVIDER=${{ github.CLOUD_PROVIDER }}" >> .env
          echo "CLOUD_NAME=${{ github.CLOUD_NAME }}" >> .env
          echo "CLOUD_API_KEY=${{ github.CLOUD_API_KEY }}" >> .env
          echo "CLOUD_API_SECRET=${{ github.CLOUD_API_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ github.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ github.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URL=${{ github.GOOGLE_REDIRECT_URL }}" >> .env
          echo "CHAT_GPT_URL=${{ github.CHAT_GPT_URL }}" >> .env
          echo "CHAT_GPT_TOKEN=${{ github.CHAT_GPT_TOKEN }}" >> .env
          echo "CHAT_GPT_MODEL=${{ github.CHAT_GPT_MODEL }}" >> .env

      # Copy selected files to remote machine
      - name: Copy selected files
        run: |
          mkdir deploy
          cp -r dist prisma package.json ecosystem.config.js package-lock.json .env deploy/

      # Copy project to remoute machine
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./deploy/
          remote_path: /home/user/pean_api/
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}
